Add packages for building paramiko
confluentinc/cp-docker-images pull request #762
Opened 2019-07-22 12:24 UTC by yangxi

/usr/local/bin/dup needs the paramiko that needs build-essential libssl-dev libffi-dev python-dev.

2019-07-23 05:40 UTC, xli1996 approved these changes

2019-07-23 23:30 UTC, ewencp reviewed
what's going on with all the commits? was the starting point for this not the right branch that's currently being targeted? seems like this also has a bunch of version change diffs.

2019-07-24 22:08 UTC, dnozay requested changes

2019-07-24 22:08 UTC, dnozay commented on Makefile
> +CONFLUENT_MINOR_VERSION ?= 4
5.3.0-post is for 5.3.0.

2019-07-28 06:34 UTC, yangxi commented
@ewencp Yeah, sorry, wrong target branch, it should target the master branch.

2019-07-29 15:11 UTC, dnozay approved these changes
👍

2019-07-29 21:27 UTC, ewencp approved these changes

2019-07-30 02:21 UTC, merged